# Créé par LM CONSTRUCTIONS, le 20/10/2020 en Python 3.7
import turtle
def carré():
    turtle.position()
(0.00,0.00)
def triangle():
    turtle.position()
(0.00,0.00)
turtle.color('red')
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(40)
turtle.penup()
turtle.forward(30)
turtle.pendown()

turtle.color('orange')
turtle.forward(40)
turtle.right(120)
turtle.forward(40)
turtle.right(120)
turtle.forward(40)
turtle.right(120)
turtle.penup()
turtle.forward(60)
turtle.pendown()

turtle.color('yellow')
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.penup()
turtle.forward(30)
turtle.pendown()

turtle.color('green')
turtle.forward(50)
turtle.right(120)
turtle.forward(50)
turtle.right(120)
turtle.forward(50)
turtle.right(120)
turtle.penup()
turtle.forward(70)
turtle.pendown()

turtle.color('blue')
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.penup()
turtle.forward(80)
turtle.pendown()

turtle.color('cyan')
turtle.forward(60)
turtle.right(120)
turtle.forward(60)
turtle.right(120)
turtle.forward(60)
turtle.right(120)
turtle.penup()
turtle.forward(80)
turtle.pendown()

turtle.color('pink')
turtle.forward(70)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(70)
turtle.penup()
turtle.forward(30)
turtle.pendown()

turtle.color('purple')
turtle.forward(70)
turtle.right(120)
turtle.forward(70)
turtle.right(120)
turtle.forward(70)
turtle.right(120)
turtle.penup()
turtle.forward(90)
turtle.pendown()

turtle.color('grey')
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(80)
turtle.penup()
turtle.forward(30)
turtle.pendown()

turtle.color('black')
turtle.forward(80)
turtle.right(120)
turtle.forward(80)
turtle.right(120)
turtle.forward(80)
turtle.right(120)
turtle.penup()
turtle.forward(81)
turtle.pendown()
